apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubernetes-scanner.fullname" . }}
  labels:
    {{- include "kubernetes-scanner.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  "config.yaml": |
    metricsAddress: ":{{ .Values.metrics.port }}"
    clusterName: "{{ .Values.config.clusterName }}"
    organizationID: {{ required "An organizationID is required!" .Values.organizationID }}
    scanning:
      requeueAfter: {{ .Values.config.scanning.requeueAfter }}
      types:
        {{- toYaml .Values.config.scanning.types | nindent 8 }}
    egress:
      httpClientTimeout: {{ .Values.config.egress.httpClientTimeout }}
      snykAPIBaseURL: {{ .Values.config.egress.snykAPIBaseURL }}

